#!/usr/bin/env bash

set -euo pipefail

ip=`curl -s -H "Authorization: Bearer $LINODE_AUTH_TOKEN" \
  https://api.linode.com/v4/linode/instances \
  | jq .data[].ipv4[0] \
  | sort -R \
  | head -n1 \
  | tr -d '"'`

ssh ricardo@$ip
