DOTFILES="$HOME/.dotfiles"

source "$DOTFILES/zsh/options.zsh"
source "$DOTFILES/zsh/completion.zsh"
source "$DOTFILES/zsh/key-bindings.zsh"
source "$DOTFILES/zsh/spectrum.zsh"
source "$DOTFILES/zsh/theme-and-appearance.zsh"
source "$DOTFILES/zsh/robbyrussell.zsh-theme"
source "$DOTFILES/zsh/forgit.zsh"

source "$DOTFILES/shell/path.sh"
source "$DOTFILES/shell/nix.sh"
source "$DOTFILES/shell/directories.sh"
source "$DOTFILES/shell/docker.sh"
source "$DOTFILES/shell/fzf.sh"
source "$DOTFILES/shell/general.sh"
source "$DOTFILES/shell/git.sh"
source "$DOTFILES/shell/hub.sh"
source "$DOTFILES/shell/prompt.sh"
source "$DOTFILES/shell/rails.sh"
source "$DOTFILES/shell/direnv.sh"
source "$DOTFILES/shell/gpg.sh"
source "$DOTFILES/shell/buildkite.sh"
source "$DOTFILES/shell/rununtilfail.sh"
source "$DOTFILES/shell/cheat.sh"
source "$DOTFILES/shell/secrets.sh"
source "$DOTFILES/shell/sdk.sh"
