" Load vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'danro/rename.vim'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-cucumber'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/matchit.zip'
" Plug 'ycm-core/YouCompleteMe'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neoclide/coc-solargraph'

let g:coc_global_extensions = ['coc-solargraph']

Plug 'w0rp/ale'

let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'
let g:ale_set_highlights = 0

let g:ale_fixers = {
\  'typescript': ['prettier'],
\  'javascript': ['eslint', 'prettier'],
\  'ruby': ['rubocop'],
\ }

let g:ale_fix_on_save = 1

Plug 'jeetsukumaran/vim-buffergator'

let g:buffergator_show_full_directory_path = 0
let g:buffergator_viewport_split_policy = "B"

syntax on

let g:solarized_termcolors=256
set t_Co=256

" You need to install https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized in your terminal
" Plug 'altercation/vim-colors-solarized'
" see more at plug#end

Plug 'dracula/vim', { 'as': 'dracula' }
let g:airline_theme='dracula'
let g:dracula_italic = 0
set background=dark
" see more at plug#end

set cursorline
set cursorcolumn

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'

" Use CTRL-P for FZF
nmap <C-P> :FZF<CR>

nnoremap K :Rg <C-R><C-W><CR>

command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)

nmap <C-P><C-P> :FZF<CR>platform_api

Plug 'godlygeek/tabular'

inoremap <silent> <Bar>   <Bar><Esc>:call <SID>align()<CR>a

function! s:align()
  let p = '^\s*|\s.*\s|\s*$'
  if exists(':Tabularize') && getline('.') =~# '^\s*|' && (getline(line('.')-1) =~# p || getline(line('.')+1) =~# p)
    let column = strlen(substitute(getline('.')[0:col('.')],'[^|]','','g'))
    let position = strlen(matchstr(getline('.')[0:col('.')],'.*|\s*\zs.*'))
    Tabularize/|/l1
    normal! 0
    call search(repeat('[^|]*|',column).'\s\{-\}'.repeat('.',position),'ce',line('.'))
  endif
endfunction

Plug 'tpope/vim-rails'

let g:rails_projections = {
  \ "app/lib/*.rb": {
  \   "test": [
  \     "spec/lib/{}_spec.rb"
  \   ],
  \ }}

set path+=app/mounts/**,frontend/components/**

Plug 'tomtom/tcomment_vim'

let g:tcomment_mapleader1 = ''
noremap <silent> <C-c> :TComment<cr>
vnoremap <silent> <C-c> :TCommentMaybeInline<cr>gv
inoremap <silent> <C-c> <c-o>:TComment<cr>

Plug 'vim-airline/vim-airline'

set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline#extensions#syntastic#enabled = 1

Plug 'vim-test/vim-test'

nmap <silent> <Leader><Leader>n :TestNearest<CR>
nmap <silent> <Leader><Leader>f :TestFile<CR>

let test#strategy = 'vimterminal'
let test#ruby#use_binstubs = 0
let test#ruby#bundle_exec = 1

Plug 'AndrewRadev/splitjoin.vim'

let g:splitjoin_trailing_comma = 1
let b:splitjoin_trailing_comma = 1
let g:splitjoin_ruby_hanging_args = 0
let b:splitjoin_ruby_hanging_args = 0
let g:splitjoin_ruby_curly_braces = 0

nmap sj :SplitjoinSplit<cr>
nmap sk :SplitjoinJoin<cr>

Plug 'lmeijvogel/vim-yaml-helper'

let g:vim_yaml_helper#auto_display_path = 0

nmap <Leader>y :YamlGoToKey
nmap <Leader>Y :YamlGetFullPath<CR>

call plug#end()

" Must come after plug#end
" colorscheme solarized
colorscheme dracula

" Aliases
cab W w
cab Q q
cab Qa! qa!
cab Qa qa
cab Wa! wa!
cab Wa wa
cab wQ wq
cab Wq wq
cab WQ wq
cab Wqa wqa
cab WQa wqa
cab WQA wqa
cab E e
cab ag Rg
cab Ag Rg
cab ack Rg
cab rg Rg
cab TAbnew tabnew
cab Tabnew tabnew
cab REname Rename
cab Renaem Rename
cab REnaem Rename
cab gb GB
cab Gb GB
cab gbrowse GBrowse
cab Gbrowse GBrowse
cab gblame Git blame
cab GBlame Git blame
cab Gblame Git blame
ab bp binding.pry
ab tt ActsAsTenant.current_tenant
ab aat ActsAsTenant
ab sos save_and_open_screenshot <esc>
ab sop save_and_open_page <esc>

" brew install uptech/oss/alt

function! AltCommand(path, vim_command)
  let l:alternate = system("find . -path ./_site -prune -or -path ./target -prune -or -path ./.DS_Store -prune -or -path ./_build -prune -or -path ./build -prune -or -path tags -prune -or -path ./tmp -prune -or -path ./log -prune -or -path ./.git -prune -or -type f -print | alt -f - " . a:path)
  if empty(l:alternate)
    echo "No alternate file for " . a:path . " exists!"
  else
    exec a:vim_command . " " . l:alternate
  endif
endfunction

" Find the alternate file for the current path and open it
nnoremap <leader>av <cr>:call AltCommand(expand('%'), ':vs')<cr>

" Find the alternate file for the current path and open it
nnoremap <leader>as <cr>:call AltCommand(expand('%'), ':sp')<cr>

" Auto complete
let g:stop_autocomplete=0

filetype plugin indent on

autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neoclide/coc-solargraph'

let g:coc_global_extensions = ['coc-solargraph']

inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" taken from jasoncodes/dotfiles vim/config/auto_mkdir.vim

function s:AutoMkdir(file, buf)
  if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
    let dir=fnamemodify(a:file, ':h')
    if !isdirectory(dir)
      call mkdir(dir, 'p')
    endif
  endif
endfunction

autocmd BufWritePre * :call s:AutoMkdir(expand('<afile>'), +expand('<abuf>'))

au BufNewFile,BufRead *.thor       set filetype=ruby
au BufNewFile,BufRead Guardfile    set filetype=ruby
au BufNewFile,BufRead .pryrc       set filetype=ruby
au BufNewFile,BufRead Vagrantfile  set filetype=ruby
au BufNewFile,BufRead *.pp         set filetype=ruby
au BufNewFile,BufRead *.prawn      set filetype=ruby
au BufNewFile,BufRead Appraisals   set filetype=ruby
au BufNewFile,BufRead Capfile      set filetype=ruby
au BufNewFile,BufRead *.rabl       set filetype=ruby
au BufNewFile,BufRead .psqlrc      set filetype=sql
au BufNewFile,BufRead *.less       set filetype=css
au BufNewFile,BufRead bash_profile set filetype=sh
au BufNewFile,BufRead bashrc       set filetype=sh
au BufNewFile,BufRead zshrc        set filetype=sh
au BufNewFile,BufRead *.hbs        set filetype=html

" Autoindent with two spaces, always expand tabs:
set tabstop=2
set shiftwidth=2
set expandtab

" Folding settings
set nofoldenable

set wildmode=list:longest " make cmdline tab completion similar to bash
set wildmenu " enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ " stuff to ignore when tab completing

" Vertical / horizontal scroll off settings
set scrolloff=3
set sidescrolloff=7
set sidescroll=1

set cf " Enable error files & error jumping.
set clipboard+=unnamed " Yanks go on clipboard instead.
let g:yankring_clipboard_monitor=0
set history=256 " Number of things to remember in history.
set autowrite " Writes on make/shell commands
set ruler " Ruler on
set nu " Line numbers on
set wrap " Line wrapping on
set timeoutlen=250 " Time to wait after ESC (default causes an annoying delay)

" Highlight all search results
set incsearch
set hlsearch

"" Vmap for maintain Visual Mode after shifting > and <
vmap < <gv
vmap > >gv

" Ignore case in searches
set ignorecase

" Open splits at right side (and below)
set splitright
set splitbelow

" Never ever let Vim write a backup file! They did that in the 70's.
" Use modern ways for tracking your changes (like git), for God's sake
set nobackup
set noswapfile

set backspace=2

" Allow mouse scroll with vim in terminal
set mouse=a

set list listchars=tab:»·,trail:·
autocmd BufWritePre * :%s/\s\+$//e

" Mapping Y to yank from current cursor position till end of line
noremap Y y$

" A trick for when you forgot to sudo before editing a file that requires root privileges (typically /etc/hosts).
" This lets you use w!! to do that after you opened the file already:
cmap w!! w !sudo tee % >/dev/null

" Search and replace selected text (http://stackoverflow.com/questions/676600/vim-search-and-replace-selected-text)
vnoremap <C-r> "hy:%s/<C-r>h//gc<left><left><left>

" F12 reloads the ~/.vimrc file
nnoremap <F12> :source ~/.vimrc<CR>

"clean up search
map <C-L> :noh<CR>:redraw!<CR>

" Improve 'n' command (for searches)
nmap n nzz
nmap N Nzz

"key mapping for tab navigation
nmap <Tab> gt
nmap <S-Tab> gT

"Disable visualbell
set visualbell
set t_vb=

" Jump between ctags and don't lose buffer history
set hidden

" Dont create new buffers
set switchbuf=useopen

" Search for visual selected text
vnoremap # y/<C-R>"<CR>

" saving that shift press
map ; :

" Let vim decide which regexpengine it's going to use
" 1 is faster for ruby, 2 is faster for typescript
" 0 means automatic decide
set regexpengine=0

" Git - Always turn on spell check
autocmd FileType gitcommit setlocal spell

"key mapping for window navigation
" map <C-h> <C-w>h
" map <C-j> <C-w>j
" map <C-k> <C-w>k
" map <C-l> <C-w>l

" Resize splits
nnoremap <D-left> :vertical resize -5<cr>
nnoremap <D-down> :resize +5<cr>
nnoremap <D-up> :resize -5<cr>
nnoremap <D-right> :vertical resize +5<cr>

" Open file under cursor in a new vertical split
nnoremap <C-W><C-F> <C-W>vgf

" taken from jasoncodes/dotfiles vim/config/undo.vim

if !isdirectory(expand("~/.vim/.undo/"))
  silent !mkdir -p ~/.vim/.undo/
endif
set undodir=$HOME/.vim/.undo
set undofile
set undolevels=1000
set undoreload=10000
