########## Alias ##########

alias ll='ls -la'
alias pj='python -mjson.tool'
alias curl='nocorrect curl'
alias meteor='nocorrect meteor'
alias Grep='grep'
alias gpre='grep'
alias grpe='grep'
alias gtix='gitx'
alias gti='git'

## Rails
alias ss='script/server'
alias sc='script/console'
alias bx='bundle exec'
alias rspec='bundle exec rspec'
alias rake='bundle exec rake'
alias rails='bundle exec rails'
alias cap='bundle exec cap'
alias guard='bundle exec guard'
alias rc='rails console'
alias bxc='rails console'
alias rs='rails server'
alias rials='rails'
alias dcm='rake db:drop db:create db:migrate'
alias dcmt='rake db:drop db:create db:migrate db:test:prepare'
alias dcmts='rake db:drop db:create db:migrate db:test:prepare db:seed'
alias z='zeus'

alias beforepostgres='sudo sysctl -w kern.sysv.shmmax=16777216; sudo sysctl -w kern.sysv.shmall=65536'
alias pgstart='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'

n() { cd ~/workspace/netengine/$1; }
_n() { _files -W ~/workspace/netengine -/; }
compdef _n n

function hlr {
  filename=`echo $1 | cut -d . -f 1`
  highlight --syntax ruby -k Menlo -K 22 -O rtf -s edit-xcode $1 > $filename.rtf
  open $filename.rtf
}

function spoof_mac_address {
  sudo ifconfig en1 ether `openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'`
}

tree() { find $1 | sed -e 's;[^/]*/;|__;g;s;__|;  |;g'; }

