########## Alias ##########

alias fastcop='git since-master | grep \\.rb$ | xargs ls 2>/dev/null | xargs rubocop --force-exclusion'
alias psg="ps aux | grep -v grep | grep -i --color=auto $1"
alias ll='ls -lah --color'
alias ls='ls -h --color'
alias lsg='ll | grep'
alias pj='python -mjson.tool'
alias curl='nocorrect curl'
alias meteor='nocorrect meteor'
alias Grep='grep'
alias gpre='grep'
alias grpe='grep'
alias gtix='gitx'
alias gti='git'
alias ag='ag -i'
alias cl='highlight -O ansi'
alias -g C='| wc -l'
alias -g H='| head'
alias -g L="| less"
alias -g S='| sort'
alias -g G='| grep' # now you can do: ls foo G something

# find all files containing $1 in the name
function lsf() { ls **/*$1* }

## Rails
alias ss='script/server'
alias sc='script/console'
alias bx='bundle exec'
alias rspec='bundle exec rspec'
alias rake='bundle exec rake'
alias rails='bundle exec rails'
alias cap='bundle exec cap'
alias guard='bundle exec guard'
alias sidekiq='bundle exec sidekiq'
alias rc='rails console'
alias bxc='rails console'
alias rs='rails server'
alias rials='rails'
alias dcm='rake db:drop db:create db:migrate'
alias dcmt='rake db:drop db:create db:migrate db:test:prepare'
alias dcmts='rake db:drop db:create db:migrate db:test:prepare db:seed'
alias bower='noglob bower'

alias beforepostgres='sudo sysctl -w kern.sysv.shmmax=16777216; sudo sysctl -w kern.sysv.shmall=65536'
alias pgstart='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'

##### Docker
eval "$(docker-machine env default)"

alias d="docker"
alias dst="docker stop"
alias drm="docker rm"
alias dps="docker ps -a"
alias dmi="docker images"
alias drun="docker run"
alias doco='docker-compose'

dclean() {
  docker rm $(docker ps -aq)
  docker rmi $(docker images | grep none | awk '{ print $3; }')
}

dbash() {
  docker exec -t -i $1 /bin/bash
}

dstoprm() {
  docker stop $1 ; docker rm $1
}

e() { cd ~/Code/$1; }
_e() { _files -W ~/Code -/; }
compdef _e e

ec() { cd ~/Code/payments/components/$1; }
_ec() { _files -W ~/Code/payments/components -/; }
compdef _ec ec

function hlr {
  filename=`echo $1 | cut -d . -f 1`
  highlight --syntax ruby -k Menlo -K 22 -O rtf -s edit-xcode $1 > $filename.rtf
  open $filename.rtf
}

function spoof_mac_address {
  sudo ifconfig en1 ether `openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'`
}

tree() { find $1 | sed -e 's;[^/]*/;|__;g;s;__|;  |;g'; }

# ZSH completion trash
export ZDOTDIR="$HOME/.oh-my-zsh"

# rbenv
if [ -d "$HOME/.rbenv" ]
then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# Node versioning
if [ -d "$HOME/.nvm" ]
then
  export NVM_DIR="$HOME/.nvm"
  . "$(brew --prefix nvm)/nvm.sh"
fi

# Autoload node version
autoload -U add-zsh-hook
load-nvmrc() {
  if [[ -f .nvmrc && -r .nvmrc ]]; then
    nvm use
  fi
}
add-zsh-hook chpwd load-nvmrc

# Direnv - Require brew install direnv
eval "$(direnv hook zsh)"

export CUCUMBER_FORMAT=progress

### Require brew install hub
eval "$(hub alias -s)"
fpath=(~/.dotfiles/zsh/_hub $fpath)
autoload -U compinit && compinit
